### ISSUE TITLE
Cython 3.0 compatibility and performance

### ISSUE THREAD

**Issue by mtreinish** [Qiskit-Extensions/mthree#188]
Cython 3.0 was a major release [1] so we'll have to evaluate compatibility in mthree with it.

[1] https://cython.readthedocs.io/en/latest/src/changes.html#unified-release-notes

_Originally posted by @mtreinish in https://github.com/Qiskit-Extensions/mthree/pull/187#pullrequestreview-1628845042_

As reported in #187 there is noticeable performance regression when building mthree from source with Cython >= 3.0. Before we say we support building with cython 3.0 we should get to the bottom of that.

**Comment by nonhermitian** [comment]
I think this is due to #197
