### ISSUE TITLE
Set up GitHub Pages and deploy the docs

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit-Extensions/mthree#198]
The project now has the workflows to deploy the documentation to a branch called gh-pages, but we need to perform the first deployment and set up the repo to use GitHub Pages by following these instructions. Once the GitHub Pages is set up please update the repo's About section to display the new link.

- [x] Deployment to the `gh-pages` branch
- [x] Set up GitHub Pages

### Instructions 

> [!WARNING]
Before starting with the process, you need to add a new branch called `gh-pages`. This branch needs to have that name to ensure the workflows can deploy successfully. You can create it manually, or, in case you have the new workflows, it will be created automatically after the first deployment (Better option).

Once you have the branch `gh-pages` created, you can follow the following steps:

1. Navigate to your site's repository
2. Click `Settings`
3. Go to `Pages`
4. Select `Deploy from a branch`, under the `Source` section on `Build and deployment`
5. Select the `gh-pages` branch and the `/ (root)` folder in the `Branch` section on `Build and deployment`

![GitHubPages-example](https://github.com/Qiskit/ecosystem/assets/47946624/520f4f0c-905a-4a4f-b918-a580a953e80d)

The default URL where you can find your site is https://qiskit-extensions.github.io/mthree

For further information, you can see the [GitHub Pages Quickstart](https://docs.github.com/en/pages/quickstart#creating-your-website) and https://github.com/Qiskit/ecosystem/issues/578.

**Comment by mtreinish** [comment]
https://qiskit-extensions.github.io/mthree/
